"""blogpost and comments table

Revision ID: 08ab55f57451
Revises: 70cf5ea0e000
Create Date: 2018-06-04 21:50:47.689116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ab55f57451'
down_revision = '70cf5ea0e000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_timestamp'), 'blog_post', ['timestamp'], unique=False)
    op.create_table('blog_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comment_timestamp'), 'blog_comment', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_comment_timestamp'), table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_index(op.f('ix_blog_post_timestamp'), table_name='blog_post')
    op.drop_table('blog_post')
    # ### end Alembic commands ###
