"""blogpost score

Revision ID: 3edfdcb50a6f
Revises: 5cce3ea8bf92
Create Date: 2018-07-21 17:29:38.673640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edfdcb50a6f'
down_revision = '5cce3ea8bf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('post_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'post_score')
    # ### end Alembic commands ###
