"""email in comments table

Revision ID: 5a1d092dc190
Revises: e4354ca301ca
Create Date: 2018-06-06 22:51:34.025934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1d092dc190'
down_revision = 'e4354ca301ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_blog_comment_email'), 'blog_comment', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_comment_email'), table_name='blog_comment')
    op.drop_column('blog_comment', 'email')
    # ### end Alembic commands ###
