"""blog photos

Revision ID: 5cce3ea8bf92
Revises: c057d2b16ef0
Create Date: 2018-07-19 22:29:37.638517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cce3ea8bf92'
down_revision = 'c057d2b16ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('photo_alt_text', sa.String(length=140), nullable=True))
    op.add_column('blog_post', sa.Column('photo_filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'photo_filename')
    op.drop_column('blog_post', 'photo_alt_text')
    # ### end Alembic commands ###
