"""HomePageContent

Revision ID: 9ab7c504b841
Revises: ef6df75fd7c5
Create Date: 2018-08-02 18:07:10.809577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab7c504b841'
down_revision = 'ef6df75fd7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('text_body', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_page_content')
    # ### end Alembic commands ###
