"""author in comments table

Revision ID: d9541df700e4
Revises: 5a1d092dc190
Create Date: 2018-06-06 22:54:39.983159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9541df700e4'
down_revision = '5a1d092dc190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_comment', sa.Column('author', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_comment', 'author')
    # ### end Alembic commands ###
