"""portfolio projects

Revision ID: fb800a6e144c
Revises: 3edfdcb50a6f
Create Date: 2018-08-01 00:07:58.370798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb800a6e144c'
down_revision = '3edfdcb50a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portf_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=3000), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cover_img_filename', sa.String(length=32), nullable=True),
    sa.Column('cover_img_alt_txt', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portf_project_timestamp'), 'portf_project', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portf_project_timestamp'), table_name='portf_project')
    op.drop_table('portf_project')
    # ### end Alembic commands ###
